#端口
server:
  port: 8101
  enable-self-preservation: false

spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: sca1,sca2
      sca1:
        jdbcUrl: jdbc:mysql://*:3308/sca1?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: *
        password: *
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
      sca2:
        jdbcUrl: jdbc:mysql://*:3309/sca2?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: *
        password: *
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
    sharding:
      defaultDataSourceName: sca1
      broadcastTables:
      - sys_user
    pro ps:
      sql:
        #生产环境关闭
        show: true
#日志
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/*/*.xml,classpath:mapper/*/*/*.xml
  configuration:
    #当查询数据为空时字段返回为null，不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true